version: "3.7"

services:
  api:
    build: ./api
    environment:
      - CONNECTION_STRING=MySQL://demo_user:demo_user@db/demo_db
    depends_on:
      - db
    networks:
      - network-hackthon

  webapp:
    build: ./web
    environment:
      - API_URL=http://api:3000/data
    depends_on:
      - api
    ports:
      - "3030:3000"
    networks:
      - network-hackthon

  db:
    image: mysql:latest
    environment:
      MySQL_USER: demo_user
      MySQL_PASSWORD: demo_user
      MySQL_DB: demo_db
    volumes:
      - ./init_sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - network-hackthon

networks:
  network-hackthon